### ISSUE TITLE
Wont eat more than 2G RAM

### ISSUE THREAD

**Issue by fungusakafungus** [samcday/elasticsearch-oomonster#1]
Haven't tested it, but noticed this line: https://github.com/samcday/elasticsearch-oomonster/blob/master/src/main/java/org/elasticsearch/plugin/oomonster/OomCatAction.java#L52

Not so hungry after all :)

**Comment by samcday** [comment]
Working as intended. Oomonster is trying to stay in shape. Do you know how many empty calories there are in every mb of RAM?

**Comment by samcday** [comment]
Actually, I was gonna fix this but there's nothing to fix - your calculation (`(2^31-1)/1024/1024/1024`) isn't factoring in the fact that each list item is a 1mb `ByteBuffer`. So actually the maximum amount of memory oomonster will eat is `(2^31-1)*1024*1024/1024/1024/1024` - 2PB :)

**Comment by fungusakafungus** [comment]
Oh, now I see it. Sorry!
